# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170216_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffwithskills',
            name='hoursLeft',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
