# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffwithskills_hoursleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectswithskills',
            name='endDate',
            field=models.DateField(default=datetime.date(2017, 2, 16)),
        ),
        migrations.AddField(
            model_name='projectswithskills',
            name='startDate',
            field=models.DateField(default=datetime.date(2017, 2, 16)),
        ),
    ]
