# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170216_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffwithprojects',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.skills'),
        ),
        migrations.AlterField(
            model_name='projectswithskills',
            name='endDate',
            field=models.DateField(default=datetime.date(2017, 2, 17)),
        ),
        migrations.AlterField(
            model_name='projectswithskills',
            name='startDate',
            field=models.DateField(default=datetime.date(2017, 2, 17)),
        ),
    ]
