# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170217_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectswithskills',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectswithskills',
            name='startDate',
            field=models.DateField(),
        ),
    ]
