# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170217_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffwithprojects',
            name='skills',
        ),
    ]
