# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_staffwithprojects_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffwithprojects',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffwithprojects',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
