# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170218_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffProjectSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('seenDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'Seen', b'Seen'), (b'Unseen', b'Unseen')], default=b'Unseen', max_length=30)),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.projects')),
                ('skillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.skills')),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'db_table': 'staffProjectSkill',
            },
        ),
    ]
