# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffprojectskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprojectskill',
            name='seenDate',
        ),
        migrations.RemoveField(
            model_name='staffprojectskill',
            name='status',
        ),
    ]
