# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170225_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffwithskills',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
