# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_skills_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='priority',
            field=models.CharField(choices=[(b'High', b'High'), (b'Mid', b'Mid'), (b'Low', b'Low')], max_length=30),
        ),
    ]
