# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20170316_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomments',
            name='time',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
