# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_boardcomments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomments',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
