# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20170316_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcomments',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardcomments',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='messageboard',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='messageboard',
            name='projectID',
        ),
        migrations.DeleteModel(
            name='boardComments',
        ),
        migrations.DeleteModel(
            name='messageBoard',
        ),
    ]
