# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20170316_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[(b'Admin', b'Admin'), (b'Project Manager', b'Project Manager'), (b'Employee', b'Employee'), (b'Contractor', b'Contractor')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workStatus',
            field=models.CharField(choices=[(b'Working', b'Working'), (b'On Leave ', b'On Leave'), (b'Not Employeed', b'Not Employeed')], max_length=15),
        ),
    ]
