# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170107_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='alertType',
            field=models.CharField(choices=[(b'Project', b'Project'), (b'Leave', b'Leave'), (b'Staff', b'Staff'), (b'Edit Project', b'Edit Project'), (b'Edit Staff', b'Edit Staff')], max_length=30),
        ),
    ]
