# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170325_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomments',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
