# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20170117_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='types',
            field=models.CharField(blank=True, choices=[(b'Consultancy', b'Consultancy'), (b'Development', b'Development'), (b'Delivery', b'Delivery')], max_length=30, null=True),
        ),
    ]
