# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_projects_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='types',
        ),
    ]
