# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_projects_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[(b'Consultancy', b'Consultancy'), (b'Development', b'Development'), (b'Delivery', b'Delivery')], max_length=30),
        ),
    ]
