# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20170117_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='alertType',
            field=models.CharField(choices=[(b'Project', b'Project'), (b'Leave', b'Leave'), (b'Staff', b'Staff'), (b'Edit Project', b'Edit Project'), (b'Edit Staff', b'Edit Staff'), (b'Project Request', b'Project Request')], max_length=30),
        ),
    ]
