# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20170121_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='type',
            field=models.CharField(blank=True, choices=[(b'Sick', b'Sick'), (b'Emergency', b'Emergency'), (b'Vacation', b'Vacation')], max_length=30, null=True),
        ),
    ]
