# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_holidays_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='type',
            field=models.CharField(choices=[(b'Sick', b'Sick'), (b'Emergency', b'Emergency'), (b'Vacation', b'Vacation')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
