# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20170122_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidays',
            name='staffID',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='holiday',
        ),
        migrations.DeleteModel(
            name='holidays',
        ),
    ]
