# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20170122_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('holidayID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('type', models.CharField(choices=[(b'Sick', b'Sick'), (b'Emergency', b'Emergency'), (b'Vacation', b'Vacation')], max_length=30)),
                ('status', models.CharField(choices=[(b'Approved', b'Approved'), (b'Declined', b'Declined')], max_length=30)),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
        migrations.AddField(
            model_name='alerts',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.holidays'),
        ),
    ]
