# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20170122_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[(b'Consultancy', b'Consultancy'), (b'Development', b'Development'), (b'Delivery', b'Delivery'), (b'IT', b'IT')], max_length=30),
        ),
    ]
