# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20170122_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='status',
            field=models.CharField(choices=[(b'Approved', b'Approved'), (b'Pending Approval', b'Pending Approval'), (b'Declined', b'Declined')], max_length=30),
        ),
    ]
